# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

/var/log/mediawiki/*.log {
    size 64M
    rotate 4
    dateext
    dateformat .%Y%m%d%H%M%S
    extension .log
    missingok
    notifempty
    copytruncate
}
