{
 "title": "MediaWiki Operator Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "global_filters" }
  ]
 },
 "panels": [
  {
   "title": "MediaWiki K8s operator",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "# MediaWiki K8s operator\n\n- Github [URL](https://github.com/canonical/mediawiki-k8s-operator)\n- For more information, visit [Charmhub](https://charmhub.io/mediawiki-k8s)\n\n"
   }
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 } },
  { "title": "MediaWiki", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Logs - MediaWiki",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{juju_application=~\"$juju_application\", pebble_service=~\"mediawikiLogs|logrotate\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\"$juju_unit\"}"
    }
   ]
  },
  {
   "title": "Logs - Job runner service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{juju_application=~\"$juju_application\", pebble_service=~\"redisJobRunnerService|redisJobChronService\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\"$juju_unit\"} |= \"\""
    }
   ]
  },
  { "title": "Apache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Apache version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_version{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache workers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (apache_workers{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache scoreboard statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum by(state) (apache_scoreboard{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache access rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(apache_accesses_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Apache request duration (percentile)",
   "type": "timeseries",
   "description": "Over a 5-minute interval.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.50,\n  {pebble_service=\"mediawiki\"}\n  | logfmt request_duration_microseconds, path\n  | path != \"/server-status\"\n  | unwrap request_duration_microseconds\n  [5m]\n)",
     "legendFormat": "P50"
    },
    {
     "expr": "quantile_over_time(0.90,\n  {pebble_service=\"mediawiki\"}\n  | logfmt request_duration_microseconds, path\n  | path != \"/server-status\"\n  | unwrap request_duration_microseconds\n  [5m]\n)",
     "legendFormat": "P90"
    },
    {
     "expr": "quantile_over_time(0.95,\n  {pebble_service=\"mediawiki\"}\n  | logfmt request_duration_microseconds, path\n  | path != \"/server-status\"\n  | unwrap request_duration_microseconds\n  [5m]\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "quantile_over_time(0.99,\n  {pebble_service=\"mediawiki\"}\n  | logfmt request_duration_microseconds, path\n  | path != \"/server-status\"\n  | unwrap request_duration_microseconds\n  [5m]\n)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Apache load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "apache_load{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{interval}}"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(apache_duration_ms_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]) / increase(apache_accesses_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Apache sent rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(apache_sent_kilobytes_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "apache_cpuload{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Logs - Apache",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "{juju_application=~\"$juju_application\", pebble_service=\"mediawiki\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\"$juju_unit\"} |= \"\""
    }
   ]
  },
  { "title": "Git Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Logs - Git Sync",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "{juju_application=~\"$juju_application\", pebble_service=\"git-sync\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\"$juju_unit\"} |= \"\""
    }
   ]
  },
  {
   "title": "Git Sync rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(git_sync_count_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Git Sync duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(git_sync_duration_seconds_sum{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval])) / sum by(status) (rate(git_sync_duration_seconds_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$__rate_interval]))",
     "legendFormat": "{{juju_unit}} {{status}}"
    }
   ]
  }
 ]
}